sudo: false
language: node_js
node_js:
  - "6.2"
compiler: clang-3.8
env:
  - CXX=clang-3.8
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-4.8
